Lock down file permissions
Only give permission to the current user, never to the group or other.
Only mixins/plugins and scripts should be executable.
When porter accesses files, it checks that there aren't any
credentials/parameteres/claims with wide-open permissions.
This check is skipped on Windows because files by default are not
shared, and Go can't accurately report file permissions on Windows.

$ porter --debug list --debug-plugins
Resolved porter binary from /usr/local/bin/porter to /Users/carolynvs/.porter/porter
Resolved storage plugin to storage.porter.filesystem
/Users/carolynvs/.porter/porter plugin run storage.porter.filesystem
PORTER HOME: /Users/carolynvs/.porter
Checking file permissions in /Users/carolynvs/.porter

Error: could not list installations: could not read storage schema document: incorrect file permissions on /Users/carolynvs/.porter/config.toml, it should be 600. Correct it manually or by running porter storage fix-permissions.

$ porter storage fix-permissions
Resetting file permissions in /Users/carolynvs/.porter...

$ porter --debug list --debug-plugins
Resolved porter binary from /usr/local/bin/porter to /Users/carolynvs/.porter/porter
Resolved storage plugin to storage.porter.filesystem
/Users/carolynvs/.porter/porter plugin run storage.porter.filesystem
Checking file permissions in /Users/carolynvs/.porter

NAME                   CREATED      MODIFIED     LAST ACTION   LAST STATUS
bug                    2021-09-20   2021-09-20   install       succeeded
porter-hello           2021-09-20   2021-09-20   install       failed
whalegap               2021-09-14   2021-09-14   install       succeeded
mas-whales             2021-09-14   2021-09-14   install       failed
mybuns                 2021-08-10   2021-08-10   install       succeeded
spike-helm3-mysql      2021-08-02   2021-08-02   install       succeeded
helm3-mysql            2021-07-29   2021-07-29   install       succeeded
hello-keyvault         2021-07-27   2021-07-27   install       succeeded
helm-mysql             2021-06-30   2021-06-30   install       succeeded
tmp                    2021-06-30   2021-06-30   upgrade       succeeded
credentials-tutorial   2021-06-29   2021-06-29   install       succeeded
porterops              2021-06-10   2021-06-10   install       succeeded
kubernetes             2020-08-24   2020-08-24   install       succeeded
HELLO                  2020-08-17   2020-08-17   uninstall     succeeded

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>