Support Installation Specification (#1684)
* Support the Installation Spec

* Change storage protocol to mimic mongo.
* Switch the filesystem plugin to use a mongo instance in a container.
* Add a mongo plugin.
* Add installation document and rename claim -> run.
* Move all storage document formats and data access into porter.

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Fix stuff found after reading my own code...

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Rename filesystem plugin to mongodb-docker

If you are still using the filesystem plugin you will see the following
error:

Error: could not list installations: could not load storage plugin: unsupported internal storage plugin specified storage.porter.filesystem

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Fix use of SchemaVersion

Our documents store PORTER'S schema for the document. If we need to
convert that document to a CNAB representation, then we will stamp the
converted document with the appropriate schema version for that spec.

Some docs don't need it at all and I've removed it.

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Remove commented out code and document claimstore interface

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Clarify debug statement for the current namespace

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Fix copy/paste error

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Fix typos

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Fix names for plugins in our config file

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Document built-in plugins

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Fix padding for list pages

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Fix formatting

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

* Fix exmaple for mongodb-docker

Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>